[package]
name = "zero2prod"
version = "0.1.0"
authors = ["nggih <linggih.saputro@sci.ui.ac.id>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
